package com.vivero.module.reports.pdf;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.vivero.config.AppProperties;
import com.vivero.module.reports.entity.Report;
import com.vivero.shared.exception.BusinessException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.format.DateTimeFormatter;

/**
 * Generador de PDF para reportes del vivero.
 */
@Component
@RequiredArgsConstructor
public class PdfReportGenerator {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final AppProperties appProperties;

    public String generateAndStore(Report report) {
        Path reportsDir = Path.of(appProperties.getStorage().getImagesPath(), "reports");
        Path pdfPath = reportsDir.resolve("report-" + report.getId() + ".pdf");

        try {
            Files.createDirectories(reportsDir);
            Files.write(pdfPath, buildPdf(report));
            return pdfPath.toString();
        } catch (IOException ex) {
            throw new BusinessException("Failed to generate report PDF", "PDF_GENERATION_ERROR");
        }
    }

    public byte[] buildPdf(Report report) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(outputStream);
            PdfDocument pdfDocument = new PdfDocument(writer);
            Document document = new Document(pdfDocument);

            document.add(new Paragraph("Vivero Monitoring Report").setBold().setFontSize(18));
            document.add(new Paragraph("Title: " + report.getTitle()));
            document.add(new Paragraph("Patrol ID: " + report.getPatrolId()));
            document.add(new Paragraph("Generated by: " + report.getGeneratedBy().getFullName()));
            document.add(new Paragraph("Generated at: " + DATE_FORMAT.format(report.getCreatedAt())));
            document.add(new Paragraph("Summary: " + safeText(report.getSummary())));
            document.add(new Paragraph(" "));

            Table table = new Table(2);
            table.addCell("Metric");
            table.addCell("Value");
            table.addCell("Observations");
            table.addCell(String.valueOf(report.getObservationsCount()));
            table.addCell("Healthy");
            table.addCell(String.valueOf(report.getHealthyCount()));
            table.addCell("Attention");
            table.addCell(String.valueOf(report.getAttentionCount()));
            table.addCell("Danger");
            table.addCell(String.valueOf(report.getDangerCount()));

            document.add(table);
            document.close();

            return outputStream.toByteArray();
        } catch (IOException ex) {
            throw new BusinessException("Failed to build report PDF", "PDF_BUILD_ERROR");
        }
    }

    private String safeText(String value) {
        return value == null || value.isBlank() ? "No summary provided" : value;
    }
}
