services:
  robot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrotech-robot
    restart: unless-stopped
    privileged: true
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - /dev:/dev
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/i2c-1:/dev/i2c-1
